// PLACEHOLDER -- replace by running `flutterfire configure`.
//
// This file is normally auto-generated by the FlutterFire CLI and contains the
// real API keys / app IDs for your Firebase project. The values below are
// non-functional placeholders so the project compiles; the app will not connect
// to Firebase until you regenerate this file with your own project:
//
//     dart pub global activate flutterfire_cli
//     flutterfire configure
//
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform. '
          'Run `flutterfire configure` to generate real values.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc3lpO7pJDm-4ylXpIn1WisvZ-ZWVHxwA',
    appId: '1:364932956192:web:40e757eff838ac73993c45',
    messagingSenderId: '364932956192',
    projectId: 'montecarlosimulator-bda',
    authDomain: 'montecarlosimulator-bda.firebaseapp.com',
    storageBucket: 'montecarlosimulator-bda.firebasestorage.app',
    measurementId: 'G-P3DK15V30T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYcdeR36vT2iywKRAUpmQoaPMTiflUdHw',
    appId: '1:364932956192:android:8855b2221f19e85b993c45',
    messagingSenderId: '364932956192',
    projectId: 'montecarlosimulator-bda',
    storageBucket: 'montecarlosimulator-bda.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'REPLACE_ME',
    storageBucket: 'REPLACE_ME.appspot.com',
    iosBundleId: 'com.example.monteCarloSimulator',
  );
}